name: CMake

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: self-hosted

    container:
      image: ubuntu:20.04
    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: echo "test cmake"
